# Generated by Django 4.2.16 on 2024-12-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_watchlater"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlater",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
